### ISSUE TITLE
Unable to run the tests

### ISSUE THREAD

**Issue by SAGARSURI** [Lumpin-askui/Flutter-Automation#1]
Hey @Lumpin-askui 
I tried running the tests. But I get the following error. Can you help me figure out the issue:
<img width="774" alt="Screenshot 2022-08-02 at 16 35 28" src="https://user-images.githubusercontent.com/14856659/182401056-58be2537-ee8e-4fc2-8fc3-d3cbed7e6d28.png">

**Comment by Lumpin-askui** [comment]
Hi Sagar, it seem that we have a problem with APv6, could you try to replace the jest.setup.ts with following:

`import { UiControlClient, UiController } from 'askui';

// Server for controlling the operating system
let uiController: UiController;

// Client is necessary to use the askui API
// eslint-disable-next-line import/no-mutable-exports
let aui: UiControlClient;

jest.setTimeout(60 * 1000 * 60);

beforeAll(async () => {

  uiController = new UiController({
    /**
     * Select the display you want to run your tests on, display 0 is your main display;
     * ignore if you have only one display
     */
    display: 0,
    host: "::1"
  });

  await uiController.start();

  aui = await UiControlClient.build({
    uiControllerUrl: 'http://[::1]:6769'  });
  

  await aui.connect();
});

afterAll(async () => {
  await uiController.stop();

  aui.close();
});

export { aui };`

**Comment by SAGARSURI** [comment]
After replacing the code you mentioned above I get the following import error:

<img width="776" alt="Screenshot 2022-08-02 at 18 27 39" src="https://user-images.githubusercontent.com/14856659/182425628-ab3822d4-248b-4da5-9242-53c829af7ad3.png">

**Comment by Lumpin-askui** [comment]
Could you try updating the lib again with `npm up askui`. Also heres some documentation on the IPv6 case [https://docs.askui.com/docs/next/general/Troubleshooting/ipv6/](url)

**Comment by SAGARSURI** [comment]
I followed the troubleshooting section and was able to run the server but the test still failed. I get the same error which I mentioned above. Also, I have to manually start the controlui-server. It doesn't start if I run the test.

**Comment by Lumpin-askui** [comment]
Wrote you a PN in Discord

**Comment by Lumpin-askui** [comment]
issue closed with pn
